name: Release

on:
  push:
    branches:
      - master

jobs:
  test-and-build:
    uses: ./.github/workflows/pull-request.yml

  release-please:
    runs-on: ubuntu-latest
    needs: [test-and-build]
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore cache
        id: restore-dependencies
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: |
            ${{ runner.os }}-dependencies-${{ hashFiles('yarn.lock') }}
            ${{ runner.os }}-dependencies-

      - uses: googleapis/release-please-action@v4
        id: release
        name: 'Release, Please'
        with:
          release-type: node
          config-file: .release-please-config.json

      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: |
          yarn install --immutable
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
